ide-session.c: use #ifdef instead of #if for IDE_ENABLE_TRACE
Use #ifdef instead of #if so the compiler doesn't complain
when its undefined.

```
../src/libide/gui/ide-session.c: In function ‘save_state_to_disk’:
../src/libide/gui/ide-session.c:684:5: error: "IDE_ENABLE_TRACE" is not defined, evaluates to 0 [-Werror=undef]
  684 | #if IDE_ENABLE_TRACE
      |     ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

followup of e73f44a34c0af310575fce92ea26e310fa640788